# Generated by Django 2.0.1 on 2018-08-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imgtitle',
            field=models.FileField(default='', upload_to='', verbose_name='题图'),
        ),
        migrations.AlterField(
            model_name='article',
            name='nid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='文章id'),
        ),
    ]
