# Generated by Django 2.0.3 on 2018-03-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学生姓名')),
                ('classes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Class', verbose_name='所属班级')),
            ],
        ),
    ]
