# Generated by Django 2.0.3 on 2018-03-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180319_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_data',
            field=models.DateTimeField(auto_now=True, verbose_name='学生创建时间'),
        ),
    ]
