# Generated by Django 2.0.3 on 2018-03-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_create_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date1', models.DateTimeField(null=True, unique=True)),
                ('test_date2', models.DateTimeField(null=True, unique_for_date=True)),
                ('test_date3', models.DateTimeField(null=True, unique_for_month=True)),
                ('test_date4', models.DateTimeField(null=True, unique_for_year=True)),
            ],
        ),
    ]
