# Generated by Django 2.0.3 on 2018-03-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.CharField(default='', max_length=32, verbose_name='课程'),
        ),
    ]
